// server/src/client/src/components/CollectionCard.svelte
<script lang="ts">
    import CategoryHeader from "./CategoryHeader.svelte";
    import KeywordsList from "./KeywordsList.svelte";
    import Image from "./Image.svelte";

    import { Delete } from "~/icons";

    export let title: string;
    export let image: {
        url: string;
        width: number;
        height: number;
    };
    export let prompt: string;
    export let negativePrompt: string;
    export let onClickCopy: (text: string) => void;
    export let onClickDelete: () => void;
    export let onContextMenu: (e: MouseEvent) => void = null;

    const createKeywords = (text: string) =>
        text
            .split(",")
            .map((p) => ({
                id: Math.random(),
                name: p.trim(),
            }))
            .filter((p) => p.name);
</script>

<div class="item">
    <div class="header">
        <h2 on:contextmenu={onContextMenu}>{title}</h2>
        <button class="primary-button" on:click={onClickDelete}>
            <Delete />
            Remove
        </button>
    </div>
    <Image
        className="image"
        alt={title}
        src={image.url}
        width={image.width}
        height={image.height}
    />
    <div class="body">
        <CategoryHeader
            title="Prompt"
            onClickCopy={() => onClickCopy(prompt)}
        />
        <KeywordsList
            keywords={createKeywords(prompt)}
            onClick={(keyword) => onClickCopy(keyword.name)}
        />
        <CategoryHeader
            title="Negative Prompt"
            onClickCopy={() => onClickCopy(negativePrompt)}
        />
        <KeywordsList
            keywords={createKeywords(negativePrompt)}
            onClick={(keyword) => onClickCopy(keyword.name)}
        />
    </div>
</div>

<style lang="scss">
    .item {
        display: grid;
        grid-template-areas:
            "header header"
            "image body";
        grid-template-columns: 350px auto;
        width: 100%;
        margin-bottom: 1.5rem;
        border: 1px solid #aaa;
        border-radius: 0.5rem;
        align-items: center;

        &:nth-child(even) {
            grid-template-areas:
                "header header"
                "body image";
            grid-template-columns: auto 350px;
        }

        .header {
            grid-area: header;
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 1rem;
            flex-wrap: wrap;
            border-bottom: 1px solid #aaa;
            padding: 1.5rem;

            h2 {
                margin: 0;
            }
        }

        :global(.image) {
            padding: 1rem;
            border-radius: 1.5rem;
            grid-area: image;
            width: 350px;
            height: auto;
            object-fit: contain;
        }

        .body {
            grid-area: body;
            padding: 1.5rem;
        }

        @media (max-width: 768px) {
            width: 100%;
            grid-template-areas:
                "header"
                "image"
                "body";
            grid-template-columns: 1fr;

            &:nth-child(even) {
                grid-template-areas:
                    "header"
                    "image"
                    "body";
                grid-template-columns: 1fr;
            }

            :global(.image) {
                width: 100%;
            }
        }
    }
</style>

// packages/client/src/components/domain/CollectionCard.tsx
import type { Collection } from '~/models/types';

import { CategoryHeader } from './CategoryHeader';
import { Image } from './Image';

interface CollectionCardProps {
    collection: Collection;
    onClickCopy: (text: string) => void;
    onClickRename?: () => void;
    onClickDelete: () => void;
    renaming?: boolean;
    removing?: boolean;
}

export const CollectionCard = ({
    collection,
    onClickCopy,
    onClickRename,
    onClickDelete,
    renaming = false,
    removing = false,
}: CollectionCardProps) => {
    return (
        <article className="mb-5 grid grid-cols-1 overflow-hidden rounded-xl border border-slate-300 bg-white lg:grid-cols-[360px_minmax(0,1fr)]">
            <header className="col-span-full flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 p-4">
                <h2 className="text-lg font-semibold text-slate-900">
                    {collection.title || '(untitled)'}
                </h2>
                <div className="flex items-center gap-2">
                    {onClickRename ? (
                        <button
                            type="button"
                            onClick={onClickRename}
                            disabled={renaming}
                            className="rounded-md border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-60"
                        >
                            {renaming ? 'Renaming...' : 'Rename'}
                        </button>
                    ) : null}
                    <button
                        type="button"
                        onClick={onClickDelete}
                        disabled={removing}
                        className="rounded-md bg-red-600 px-3 py-2 text-xs font-semibold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:bg-red-400"
                    >
                        {removing ? 'Removing...' : 'Remove'}
                    </button>
                </div>
            </header>

            <Image
                className="h-auto w-full bg-slate-50 p-4 object-contain lg:w-[360px]"
                alt={collection.title}
                src={collection.image.url}
                width={collection.image.width}
                height={collection.image.height}
            />

            <div className="p-4">
                <CategoryHeader title="Prompt" onClickCopy={() => onClickCopy(collection.prompt)} />
                <p className="mb-4 rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm leading-relaxed text-slate-700 whitespace-pre-wrap">
                    {collection.prompt || '-'}
                </p>

                <CategoryHeader title="Negative Prompt" onClickCopy={() => onClickCopy(collection.negativePrompt)} />
                <p className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm leading-relaxed text-slate-700 whitespace-pre-wrap">
                    {collection.negativePrompt || '-'}
                </p>
            </div>
        </article>
    );
};
