// server/src/client/src/components/KeywordsList.svelte
<script lang="ts">
    import type { Keyword } from "../models/types";

    export let keywords: Keyword[] = [];
    export let onClick: (keyword: Keyword) => void;
    export let onContextMenu: (e: MouseEvent, keyword: Keyword) => void = null;
</script>

<ul class="prompt-list">
    {#each keywords as keyword}
        <li
            class="prompt"
            on:keydown={(e) => {
                if (e.key === "Enter") {
                    onClick(keyword);
                }
            }}
            on:click={() => onClick(keyword)}
            on:contextmenu={(e) => onContextMenu(e, keyword)}
        >
            {keyword.name}
            {#if keyword.image}
                <img
                    loading="lazy"
                    src={keyword.image.url}
                    alt={keyword.name}
                />
            {/if}
        </li>
    {/each}
</ul>

<style lang="scss">
    .prompt-list {
        position: relative;
        margin: 0;
        padding: 0;
        display: flex;
        gap: 0.5rem;
        flex-wrap: wrap;
        margin-bottom: 1rem;
    }

    .prompt {
        position: relative;
        list-style: none;
        background-color: #fff;
        padding: 0.5rem 0.8rem;
        border-radius: 0.5rem;
        cursor: pointer;

        .dragHandle {
            svg {
                width: 0.8rem;
                height: 0.8rem;
            }
        }

        img {
            display: none;
            position: absolute;
            background: #fff;
            border-radius: 0.5rem;
            bottom: 0;
            right: 0;
            width: 120px;
            height: auto;
            transform: translate(100%, 100%);
            z-index: 1;
        }

        &:hover {
            img {
                display: block;
            }
        }
    }
</style>

// packages/client/src/components/domain/KeywordsList.tsx
import type { KeyboardEvent, MouseEvent } from 'react';

import type { Keyword } from '~/models/types';

interface KeywordsListProps {
    keywords: Keyword[];
    onClick?: (keyword: Keyword) => void;
    onContextMenu?: (event: MouseEvent<HTMLLIElement>, keyword: Keyword) => void;
}

const handleEnterKey = (event: KeyboardEvent<HTMLLIElement>, onClick: (() => void) | undefined) => {
    if (event.key === 'Enter') {
        onClick?.();
    }
};

export const KeywordsList = ({ keywords, onClick, onContextMenu }: KeywordsListProps) => {
    return (
        <ul className="mb-4 flex flex-wrap gap-2">
            {keywords.map((keyword) => (
                <li
                    key={keyword.id}
                    role="button"
                    tabIndex={0}
                    onKeyDown={(event) => handleEnterKey(event, onClick ? () => onClick(keyword) : undefined)}
                    onClick={() => onClick?.(keyword)}
                    onContextMenu={(event) => onContextMenu?.(event, keyword)}
                    className="group relative list-none rounded-md border border-slate-200 bg-white px-3 py-1.5 text-xs text-slate-700 shadow-sm hover:bg-slate-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-400"
                >
                    {keyword.name}
                    {keyword.image ? (
                        <img
                            loading="lazy"
                            src={keyword.image.url}
                            alt={keyword.name}
                            className="pointer-events-none absolute -bottom-1 left-full z-20 hidden w-28 rounded-lg border border-slate-200 bg-white shadow-lg group-hover:block"
                        />
                    ) : null}
                </li>
            ))}
        </ul>
    );
};
