// packages/client/src/components/domain/CategoryHeader.tsx
import type { MouseEvent } from 'react';

import { Button } from '~/components/ui/Button';

interface CategoryHeaderProps {
    title: string;
    onClickCopy?: () => void;
    onContextMenu?: (event: MouseEvent<HTMLHeadingElement>) => void;
}

export const CategoryHeader = ({ title, onClickCopy, onContextMenu }: CategoryHeaderProps) => {
    return (
        <div className="mb-4 flex items-center justify-between gap-3">
            <h2
                className="text-base font-semibold text-ink"
                onContextMenu={onContextMenu}
            >
                {title}
            </h2>
            {onClickCopy ? (
                <Button variant="secondary" size="sm" onClick={onClickCopy}>
                    Copy all
                </Button>
            ) : null}
        </div>
    );
};

// server/src/client/src/components/CategoryHeader.svelte
<script lang="ts">
    import { Draft } from "~/icons";

    export let title: string;
    export let onClickCopy: () => void;
    export let onContextMenu: ((e: MouseEvent) => void) | null = null;
</script>

<div class="category-header">
    <h2 on:contextmenu={onContextMenu}>
        {title}
    </h2>
    <div>
        <button class="secondary-button" on:click={() => onClickCopy()}>
            <Draft />
            copy all
        </button>
    </div>
</div>

<style lang="scss">
    .category-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1.5rem;

        h2 {
            margin: 0;
            padding: 0;
        }
    }
</style>
