// packages/client/src/components/domain/Image.tsx
import { useEffect, useRef } from 'react';

interface ImageProps {
    src: string;
    alt: string;
    width?: number;
    height?: number;
    className?: string;
}

const toPreviewUrl = (src: string) => {
    const lastDot = src.lastIndexOf('.');
    if (lastDot < 0) {
        return src;
    }

    return `${src.slice(0, lastDot)}.preview.jpg`;
};

export const Image = ({ src, alt, width, height, className }: ImageProps) => {
    const ref = useRef<HTMLImageElement | null>(null);

    useEffect(() => {
        const target = ref.current;
        if (!target || !src) {
            return;
        }

        const observer = new IntersectionObserver((entries, currentObserver) => {
            entries.forEach((entry) => {
                if (!entry.isIntersecting) {
                    return;
                }

                const image = entry.target as HTMLImageElement;
                const realSource = image.dataset.src;
                if (realSource) {
                    image.src = realSource;
                }
                currentObserver.unobserve(image);
            });
        });

        observer.observe(target);

        return () => {
            observer.disconnect();
        };
    }, [src]);

    return (
        <img
            ref={ref}
            className={className}
            src={toPreviewUrl(src)}
            data-src={src}
            width={width ?? undefined}
            height={height ?? undefined}
            alt={alt}
            loading="lazy"
        />
    );
};

// server/src/client/src/components/Image.svelte
<script lang="ts">
    import { onDestroy, onMount } from "svelte";

    export let src: string;
    export let alt: string;
    export let width: number = 0;
    export let height: number = 0;
    export let className: string;

    let ref = null;
    let observer: IntersectionObserver;

    onMount(() => {
        observer = new IntersectionObserver((entries) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    const img = entry.target as HTMLImageElement;
                    img.src = img.dataset.src;
                    observer.unobserve(img);
                }
            });
        });
    });

    $: {
        if (ref && src && observer) {
            observer.observe(ref);
        }
    }

    onDestroy(() => {
        observer.disconnect();
    });
</script>

<img
    bind:this={ref}
    class={className}
    src={src.replace(src.split(".").pop(), "preview.jpg")}
    data-src={src}
    width={width ? width : "auto"}
    height={height ? height : "auto"}
    {alt}
/>
